### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by s3bq8** [DoppelKorn/Twitter-Rest-API#1]
i have erorr 

C:\xampp\htdocs\Twitter\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_NO_SUCH_TABLE: Table 'w11.benutzer' doesn't exist
    at Query.Sequence._packetToError (C:\xampp\htdocs\Twitter\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\xampp\htdocs\Twitter\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\xampp\htdocs\Twitter\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\xampp\htdocs\Twitter\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\xampp\htdocs\Twitter\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\xampp\htdocs\Twitter\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\xampp\htdocs\Twitter\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\xampp\htdocs\Twitter\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (C:\xampp\htdocs\Twitter\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\xampp\htdocs\Twitter\node_modules\mysql\lib\Connection.js:198:25)
    at IncomingMessage.<anonymous> (C:\xampp\htdocs\Twitter\server.js:72:13)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage: "Table 'w11.benutzer' doesn't exist",
  sqlState: '42S02',

**Comment by soerenpriess** [comment]
Hey, the api is connected to a database and your error says that the table "w11.benutzer" does not exist in the database you are accessing. Try to create a locale database, then set the data for your database on lines 257-263 of the code and create a table with the same name that you want to access.
